version: "3.4"

services:
  brx-template-react:
    image: brx-template
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
