version: "3.4"

services:
  sampleproject:
    image: vitereacttanstacktemplate
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
